ANTHILL_LANGUAGE: str = 'ru'
# REPORT
ANTHILL_REPORT_PREF = '.txt'
ANTHILL_REPORT_NAME = 'report'
ANTHILL_REPORT_PATH = 'report/'
ANTHILL_REPORT_ERROR_NAME = 'errors'
ANTHILL_REPORT_ERROR_PATH = 'report/errors/'
# IMAGES
ANTHILL_IMAGES_PATH = 'images/'
ANTHILL_IMAGES_BLANK_PATH = 'images/images_blank/'
ANTHILL_IMAGES_TEXT_PATH = 'images/images_text/'
# FONTS
ANTHILL_FONTS_PATH = 'fonts/'
# FACEBOOK
ANTHILL_FACEBOOK_API = "EAAKxBdAeSbwBAAY7kt2ZAvQGx6If0ZAeet70uTksc70pMSiR9WIgPWkeQWVD7Cfv5rC8rDw1KOsovRaEvyhkQZAXLCYHZCRmFaav4UzMdC54wdD2k1PKyJLV3iYsZA5Dw31zfIkub5nmyrBTHDPzDzXN9ELsxoLGCJtMRuIId4eh2enFCtOwKeJKxIB2OWG0ZD"
# DATABASE
ANTHILL_DB_PATH = 'database/'
ANTHILL_DB_NAME = 'main'
ANTHILL_DB_PREF = '.sqlite'
#TELEGRAM
ANTHILL_TELEGRAM_API = '883009969:AAE9PTeYk1lHTZ4U8fGoTXYE586wTAaXlBk'
ANTHILL_TELEGRAM_CHAT_ID = -1001404262415
