ANTHILL_LANGUAGE: str = 'ru'
# REPORT
ANTHILL_REPORT_PREF = '.txt'
ANTHILL_REPORT_NAME = 'report'
ANTHILL_REPORT_PATH = 'report/'
ANTHILL_REPORT_ERROR_NAME = 'errors'
ANTHILL_REPORT_ERROR_PATH = 'report/errors/'
# IMAGES
ANTHILL_IMAGES_PATH = 'images/'
ANTHILL_IMAGES_PRE_NAME_OUT = '_text'
# FONTS
ANTHILL_FONTS_PATH = 'fonts/'
# FACEBOOK
ANTHILL_FACEBOOK_API = "EAAKxBdAeSbwBAAY7kt2ZAvQGx6If0ZAeet70uTksc70pMSiR9WIgPWkeQWVD7Cfv5rC8rDw1KOsovRaEvyhkQZAXLCYHZCRmFaav4UzMdC54wdD2k1PKyJLV3iYsZA5Dw31zfIkub5nmyrBTHDPzDzXN9ELsxoLGCJtMRuIId4eh2enFCtOwKeJKxIB2OWG0ZD"
ANTHILL_FACEBOOK_URL = 'https://www.facebook.com/pg/krsoup/posts/'
# DATABASE
ANTHILL_DB_PATH = 'database/'
ANTHILL_DB_NAME = 'main'
ANTHILL_DB_PREF = '.sqlite'
# TELEGRAM
ANTHILL_TELEGRAM_API = '883009969:AAELgJr0ZWx8Rt5Xk4aT7vbj22HEiauvZPs'
ANTHILL_TELEGRAM_CHAT_ID = -1001404262415
# TWITTER
ANTHIL_TWITTER_TOKEN = '1187309947228430337-eTbrQpgmeaB81lT75qKhW2GceqYzfb'
ANTHIL_TWITTER_TOKEN_SECRET = 'el4OQdEsRL9VJrzZglfdUucNEIX9wu4tP9pIElCcHAUZi'
ANTHIL_TWITTER_CONSUMER = 'CkQVkzJWxLfiDHzZSNgbXc06X'
ANTHIL_TWITTER_CONSUMER_SECRET = '7qx5ZETKyTDmINKq5wk5zpCCD1Kzv7BdilAM8MceOyMCFBRuSL'
